.github/review-policy.yml
This was breaking how the review policy was being read.
=> Remove extra indentation in review policy

bot/__init__.py, bot/__main__.py, bot/bot.py, bot/exts/ping.py, bot/log.py, poetry.lock, pyproject.toml
Adds bot core to Sir Robin, utilizing the extension and logging utilities. Also adds fixes to logging, as it used to use one logger across modules.
=> Add bot-core to Sir Robin

bot/bot.py, bot/constants.py
Per a convo with @ToxicKidz, added `wait_until_guild_read` and the `send_log` method to the bot. 
[message](https://discord.com/channels/267624335836053506/943526620940083220/947328378925613107)
=> add log message on startup and on guild available

.github/workflows/status_embed.yaml
In 0.3.0 Seb's status embed action pulls the meta data driectly from the github object, so there is no need to pass it in
=> Bump status embed version to reduce args

bot/bot.py
Just a tiny PR to make extension loading compatible with Cogs that call `wait_until..` by themselves.
=> Patch Sir Robin to use a task to load in extensions

bot/utils/blurple_formatter.py
Fixed the `KeyError` occuring when `ast.JoinedStr` is looked up in the precedence table. Does not fix `ast.JoinedStr` being unparsed to a form against PEP 9001.
=> Fix `KeyError` for `ast.JoinedStr`

bot/utils/blurple_formatter.py
Fix the error for the `*args` and `**kwargs` parameters by removing the `unparse()` call because `vararg.arg`/`kwarg.arg` are already strings.
=> Fix the error for `*args` and `**kwargs` parameters

bot/utils/blurple_formatter.py
Fix the generation of the whitespace by modifying a single character in the source code.
=> Fix the problem of the formatter generating no whitespace at all

bot/utils/blurple_formatter.py
Calls `unparse` on the `lower`, `upper` and `step` arguments of a slice.
=> Fix Formatting for Slice Arguments

bot/utils/blurple_formatter.py
When formatting code, you may notice trailing lines with indents. This was because of `yield n * " " + space().join(curr_chunk)` which would generate an indent even if `curr_chunk` was empty.
=> Fix trailing indented lines

bot/exts/blurple_formatter.py, bot/utils/services.py
Formatted code can become longer than its input, this means that the message sent may go over the 2000-character limit.
This PR ports over the bot service file and puts it to good use in the blurple formatter.
=> Port hastebin to Sir Robin

bot/utils/blurple_formatter.py
Fixed formatting of `assert` statements in the blurple formatter.
https://discord.com/channels/267624335836053506/959231863698882621/959847841952567389
=> Fix `assert` formatting in blurple formatter

bot/exts/blurple_formatter.py, bot/utils/blurple_formatter.py
…constants.
Fix the f-string output to follow PEP 9001.
Fix parenthesized expressions by adding whitespace to the beginning and end of the expression.
Fix `inf`/`nan` constants not appearing correctly.
=> Fix f-strings, parenthesized expression whitespaces, and inf/nan

bot/exts/code_jams/_cog.py, bot/exts/code_jams/_creation_utils.py, bot/exts/code_jams/_views.py, bot/utils/exceptions.py
- From now on the `cj info` command has a view attached to it. You can either view all the notes added to the specific participant, or you can add one. Adding a note is accomplished by triggering a modal from the view, which then calls the code jam management api on submission.A new kind of interaction check has been implemented for this view, since from now on, all of the admins can use the view regardless of the original author.
=> Add support for viewing and adding CJ Infractions notes

bot/exts/code_jams/_cog.py, bot/exts/code_jams/_creation_utils.py, bot/exts/code_jams/_flows.py, bot/exts/error_handler.py, bot/utils/checks.py, bot/utils/exceptions.py
Lets Code Jam participants pin messages in their own team channels. Check done via the Code Jam MGMT api.
Closes #53
=> Add `cj pin` and `cj unpin`

bot/exts/code_jams/_cog.py, bot/exts/code_jams/_flows.py
This PR introduces a new command and flow, which will enable the events team to add someone to the Code Jam either as a team lead or participant.
(Note: This `add_flow` is a modified version of the `move_flow`)
=> Add `cj add` command and `add_flow` to the CJ exts stack

.github/workflows/lint-test.yaml, Dockerfile, docker-compose.yml
Poetry 1.2 introduced a regression which broke pip `--user` installs. These types of install were the main way we did installations in docker and CI, as they made it much more convenient to control the location, availability, and caching of packages.
Poetry's team does not recognize this as a supported use case, so major changes were required to get everything working again. Most of the changes were consolidated into chrislovering/python-poetry-base for docker, and HassanAbouelela/setup-python for CI.
This is part of a larger collection of PRs to python-discord projects
=> Fix Poetry 1.2 Support

.github/workflows/build_deploy.yaml
Solves part of https://github.com/python-discord/kubernetes/issues/140, since the repository is now public.
=> `REPO_TOKEN` is no more.

bot/bot.py, bot/constants.py, bot/exts/advent_of_code/__init__.py, bot/exts/advent_of_code/_caches.py, bot/exts/advent_of_code/_cog.py, bot/exts/advent_of_code/_helpers.py, bot/exts/advent_of_code/about.json, bot/exts/advent_of_code/views/dayandstarview.py, bot/utils/__init__.py, bot/utils/checks.py, bot/utils/decorators.py, bot/utils/exceptions.py, bot/utils/members.py, bot/utils/pagination.py
This is a migration of the Advent of Code cog, mostly as-is, from Sir Lancebot to Sir Robin. This is as close to a straight migration as I could manage. Any changes or improvements we want will be made in subsequent PRs once this is merged in.
I've split this up into 4 commits, grouped by collections of files/changes:
- Porting over the necessary `utils/` files
- Updating the `constants.py` file
- A quick port of the invoke help command thingy
- Migration of the Advent of Code cog itself
The commits have information about what is not quite the straight port. Spoiler alert: it's some import statements and parts of the Redis Cache. Everything else is a straight copy/paste or drag/drop.
If you'd like to test this with minimal effort, I can provide most of my `.env` file that includes the …
=> Advent of Code Migration from Sir Lancebot

bot/exts/advent_of_code/_helpers.py
Now, the command should be `&aoc join` because the prefix was changed.
The command's prefix will be dynamically added in the bad argument message. This means that if the prefix ever gets changed again, the message will be adapted automatically.
=> Fix wrong prefix in aoc join message

bot/exts/advent_of_code/views/dayandstarview.py
Discord's API now expects the interaction to be responded to, or else it will report the interaction failed. Since we an in fact defering actual feedback to the user until they press 'fetch' deferring the interaction is the correct thing to do here.
=> Defer callback response for AoC selects

bot/exts/advent_of_code/_cog.py
Uncomments the starting of the completionist role task. A better approach for future years will be taken after this event ends.
=> Start Completionist Role Assignment

.pre-commit-config.yaml, bot/exts/advent_of_code/_cog.py
We keep Advent of Code around until February (plus a week or two into February) for the AoC Completionist role. I'd like have the core commands available during the 1-2 weeks into February we keep it around for people to fix and account linking or if they finish AoC at the very end of January.
=> Extend AoC commands to Feb

.github/workflows/lint-test.yaml, Dockerfile, bot/converters.py, bot/exts/advent_of_code/_cog.py, bot/exts/advent_of_code/_helpers.py, bot/exts/code_jams/_cog.py, bot/exts/code_jams/_creation_utils.py, bot/exts/code_jams/_flows.py, bot/exts/code_jams/_views.py, bot/exts/miscellaneous.py, bot/exts/pep.py, bot/exts/source.py, bot/exts/summer_aoc.py, bot/services.py, bot/utils/__init__.py, bot/utils/checks.py, bot/utils/decorators.py, bot/utils/members.py, bot/utils/pagination.py, bot/utils/services.py, pyproject.toml, tests/_autospec.py, tests/helpers.py
This bumps sir-robin's python version to 3.11.
By the same occasion, this updates all references of `typing.Optional` and `typing.Union` to use the `|` gate.
=> Bump python version to 3.11

bot/constants.py, bot/exts/code_jams/_creation_utils.py, bot/exts/code_jams/_views.py
This corrects some permissions issues from last year:
- Adds Sir Robin to individual team channels
- Give the Event Lead roles manage_channels permission for the category
- Adds Sir Lancebot and Python to team channels and the category overall, just to be sure
Why do we have to override permissions on the individual channels when it's being added to the category is a reasonable question you might ask when looking at this PR. The answer lies in the hell that is the Discord channel permission system. When creating a channel from a category, if you override the permissions *during* creation, it will not inherit the permissions from the category. We override the permissions on creation to add the individual team roles. So therefore we need to duplicate some efforts to make sure we cover our …
=> Code Jam Permissions Update and a little bit extra

bot/constants.py, bot/exts/advent_of_code/_cog.py, bot/exts/summer_aoc.py, bot/utils/exceptions.py
Closes #99
Removes the `!subscribe`  command any references to it, since we have a new way of doing roles. Should be ready to reveiew and merge, grep seems to be returning no more results for `!subscribe`, or `subscribe`.
=> Remove `!subscribe` and references.

bot/exts/advent_of_code/_cog.py, bot/exts/core/error_handler.py, bot/exts/core/help.py, bot/utils/checks.py, bot/utils/decorators.py, bot/utils/exceptions.py
This PR updates and touches up the `&help` command output and some of the error handling. In addition, it also fixes how the channel whitelist works.
- Help command cog is shamelessly stolen from Sir Lancebot
- Error handling is updated to catch some of the new errors being thrown
- This unifies how we do the channel whitelisting and simplifies it as well
- Some general reorganization and cleanup of unused items
=> Sir Robin Error Handling & Help Command updates

bot/exts/advent_of_code/_cog.py
This removes the channel lock for `&aoc countdown`. The command response is a single line message and is useful to have in other channels.
It also adds an in-month lock decorator for the stats command. This was overlooked in previously.
=> Remove channel lock for countdown

bot/constants.py
I have all of January to create a proper start/stop command ... what could possibly go wrong.
=> Update default role id for AoC Completionist

bot/constants.py, bot/exts/advent_of_code/_caches.py, bot/exts/advent_of_code/_cog.py, bot/exts/advent_of_code/_helpers.py, bot/exts/core/error_handler.py, bot/log.py, bot/utils/decorators.py
Labeled as **DO NOT MERGE** as I will need to migrate redis caches to the new namespaces before merging this.
This adds a new command, and redis cache, to control whether the AoC completionist role is issued.
This also refactors the cog a little it while I was there. As usual, this PR is best reviewed commit-by-commit.
=> Command to toggle issuing AoC completionist

bot/exts/games.py
I was finding the current uptime to be too brief.
=> Create new command to adjust game uptime. Increase default uptime.

bot/constants.py, bot/exts/code_jams/_cog.py
Adds a command group called `support` to the code jam cog to enabling toggling of the Code Jam Support role for admins and event team members.
Closes #126
=> Add codejam support command group.

bot/exts/advent_of_code/_helpers.py
The join command is actually a slash command, but the bot tells people to do `&aoc join`, and it ends up just not working. I've seen lots of people run into this; [most recent example](https://discord.com/channels/267624335836053506/897932607545823342/1318514905195745281).
I've never worked on Discord bots so I'm not sure if this is the correct way to show slash commands (like the way it was `{Bot.prefix}` instead of just a literal ampersand), but either way it needs correction.
=> &aoc join -> /aoc join in the error message

bot/exts/smart_eval/_smart_eval_rules.py
Code containing `import this` will now have a chance of displaying [PEP 9001 revised Zen of Python](https://peps.pythondiscord.com/pep-9001/#the-revised-zen-of-python).
=> Add PEP 9001 Zen of python response

bot/exts/smart_eval/README.md, bot/exts/smart_eval/__init__.py, bot/exts/smart_eval/_cog.py, bot/exts/smart_eval/_smart_eval_rules.py
This PR brings in the following beta features:
`&smart_eval`/`&smarte` command by @janine9vn
`&donate` command by @wookie184
=> [BETA] New AI-Powered Smart Eval command

bot/exts/smart_eval/_smart_eval_rules.py
Makes both the eso-py channel link actually work, and adds some randomness to some of the default responses for flavor. Hopefully this doesn't break everything/I did it all right
=> Smart eval eso-py link + extra condition

bot/exts/smart_eval/_smart_eval_rules.py
“The measure of intelligence is the ability to change”​ - Albert Einstein.
The new general responses are @lemonyte 's suggestions.
=> Smart eval intelligence update 2

bot/exts/smart_eval/_cog.py, bot/utils/uwu.py
Now smarter and evaler than ever.
=> Smart eval intelligence update 3: UwU
